### ISSUE TITLE
[メモ]Cypressで使用する定数について

### ISSUE THREAD

**Issue by Prog24** [Prog24/cypress-component-test#8]
Cypress用にenvを設定することができる。
https://docs.cypress.io/guides/guides/environment-variables

個人的に触っていて便利だったのは `cypress.env.json` を利用する方法。
https://docs.cypress.io/guides/guides/environment-variables#Option-2-cypressenvjson

`cypress.env.example.json` などを作成しておき認証情報などを管理すると便利そう。

**Comment by Prog24** [comment]
CIを使う時には以下の様にsecretsを使って情報を入れることもできる。
```yml
      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
```
